version: "3.7"

services:
  fastapi:
    image: fastapi
    command: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8432
    ports:
      - 8432:8432
    volumes:
      - .:/code/
